
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha@aqui
      POSTGRES_DB: escola
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: escola
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha@aqui
    volumes:
      - mariadb_data:/var/lib/mysql

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: Y
      MSSQL_DBNAME: escola
    volumes:
      - sqlserver_data:/var/opt/mssql

  # adminer:
  #   image: adminer
  #   ports:
  #     - "8080:8080"

volumes:
  postgres_data:
  mariadb_data:
  sqlserver_data: